version: '3'
services:
  backend-service:
    container_name: labbook_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    networks:
      - backend
    restart: unless-stopped
    # environment:
    #   - SAVE_TO=/home/media
    #   - ALLOWED_FILE_TYPES=image/jpg,image/jpeg,image/png,image/webp
    #   - MAX_FILE_SIZE=5
    #   - PORT=4006
    #   - RATE_WINDOW=15
    #   - RATE_LIMIT=100
    #   - INTERNAL_URI=/file/
    #   - KEYCLOAK_CLIENT_ID=myclient
    #   - KEYCLOAK_URL=http://localhost:8080
    #   - KEYCLOAK_REALM=myrealm
    #   - KEYCLOAK_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtpaASGg9IVXipHTmVaSeUAQHTrAXtkrKj2LDxsyxVHPTVA9XmIq5BbZrWa5cUZ6LZaP+Ug7jhJ33UmL7QTzFPZlH//TQmyT0OyrhFw81F+3qpx3Mf1V+tOEhcq806tY2zhh6C6iQeDJ1zl9LM1lZjh6S2mILIS09HPHU16v8G5tZL98LQ5wxEfQKbim4gpYv+dFhHa/Zk+gCZL1e2msHoXY5lm5DBh6ihDmjIwH6LBShww1M4K0zjmC7fKGYUXPtTfsOz3v938f0G9JITNWYdFHPBYZO7zBPMricE0oABs8aZoQ6kSZ30Uq7uCsfT9/A0p2DAPa6w5+dKzA0FXRBXwIDAQAB\n-----END PUBLIC KEY-----
    ports:
      - "4006:4006"  
    volumes:
      - ./media:/home/media
 
  nginx-service:
    image: nginx
    container_name: labbook_nginx
    depends_on:
      - backend-service
    networks:
      - backend
    restart: unless-stopped
    ports:
      - "4005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/home/media
 
networks:
  backend:
